name: CI
on:
  push:
    branches:
    - main
jobs:
  build_for_heroku:
    runs-on: ubuntu-latest
    steps:
    - name: Build and deploy the Docker image
      uses: actions/checkout@v3
      working-directory: ./Fintech-Api-GateWay/Dockerfile
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        APP_NAME: ${{secrets.HEROKU_APP_NAME}}
      run: 
        docker build -t notify .
        docker tag notify registry.heroku.com/$APP_NAME/web
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
